name: 'Parse input template'
description: 'This template is used for parsing custom inputs as templates.'
author: 'Adam Kattan Rahmani'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  templates:
    required: true
    description: 'Provide JSON array of string in a template format.'
  vars:
    required: true
    description: "Provide JSON dictionary of 'key': 'value' encoded variables."

outputs:
  parsed-inputs:

runs:
  using: node20
  main: dist/index.js
